database:
  # Data convert is not implemented currently,
  #  but it's supposed to be able to convert from any database to a new database.
  # Data converter values are meant for the old database login details, and the ones below are
  #  for the new database connection.
  data-converter:
    # MySQL, SQLite, Mongodb?
    type: MySQL
    # Ip to the database
    host: 198.0.0.0.1
    # Port to the database
    port: 25373
    # Database name
    name: "UnityFactions"
    # The username to the db
    user: "root"
    # The password to the db
    password: "MakeStrongPasswords"

    hikari:
      minimum-pools: 5
      maximum-pools: 200
      testQuery: IGNORE

    sql:
      table:
        factions: unity_factions
        members: unity_members
        homes: unity_homes
  # MySQL, SQLite, Mongodb?
  type: MySQL
  # Ip to the database
  ip: 198.0.0.0.1
  # Port to the database
  port: 25373
  # Database name
  name: "UnityFactions"
  # The username to the db
  user: "root"
  # The password to the db
  password: "MakeStrongPasswords"
  timeout-limit: 45000
  minimum-idle: 20000

  # Hikari is used when using SQL-based databases as it allows multiple connections at a time.
  hikari:
    # The minimum idle time for a connection
    minimum-idle: 10000
    # The maximum number of connection pools
    maximum-pools: 10
    # The test query for the database
    test-query: IGNORE

  sql:
    table:
      factions: unity_factions
      members: unity_members
      homes: unity_homes

faction:
  name:
    regex: "[a-zA-Z0-9_]*"
    max: 10
    min: 3
  prefix:
    regex: "[*+-]*"
    max: 3
    min: 1

  max-owners: 2
  max-admins: 3
  max-mods: 7
  max-members: 9
  max-allies: 3

  require-members:
    5:
      mods: 1
    10:
      admins: 1
      mods: 1

#chat:
 # handle-toggle-chat: false
  #chat-handler: "GoldenDupe"

performance:
  # If this is set to false, non-administrator players cannot load offline players to the server.
  # For example, when a player executes command "/factions info -player <offline-player>"
  #  it might lag the server for a bit, because the server needs to load the offline player's data
  #   and load the faction data for the offline player.
  # The player data in faction should be that large.
  #  So it would make massive lag to the server, but it's still a possibility if the command is spammed.
  allow-offline-player-search: true
